server:
  port: 8805
  servlet:
    context-path: /system-dictionary
    session:
      timeout: 120
      cookie:
        path: /

spring:
  application:
    name: eureka-client-system-dictionary
  datasource:
    username: coss_user
    password: MysqlCossuser123Cloud!@#
    url: jdbc:mysql://127.0.0.1:3306/coss_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: coss4_dev
  session:
    store-type: mongodb
    jdbc:
      table-name: sessions

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.net.powerinv.coss4.entity

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

feign:
  hystrix:
    enabled: true
